name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

env:
  PNPM_VERSION: 10

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint:js
      - run: pnpm lint:prettier

  test:
    name: Node Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm test:node
